trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'myserviceConnection'
  location: 'eastus'
  resourceGroupName: 'rg-test-eu-001'

stages:
- stage: Build
  displayName: "Build & Publish ARM Templates"
  jobs:
    - job: Package
      displayName: "Package Templates"
      steps:
        - task: PublishPipelineArtifact@1
          displayName: "Publish Templates Artifact"
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/Templates'
            artifact: 'arm-templates'

- stage: Deploy
  displayName: "Deploy Resources"
  dependsOn: Build
  jobs:
    - template: deployment.yml
      parameters:
        azureServiceConnection: $(azureServiceConnection)
        location: $(location)
        resourceGroupName: $(resourceGroupName)
